server:
  port: 6539
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://202.194.14.120/web_2023_14?autoReconnect=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: web_2023_14
    password: Teachweb2023.14
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc   # 使用 JDBC 存储会话
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled:true
      max-file-size:200MB
      max-request-size:200MB
